//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_0_One.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservaciones
    {
        public int ID { get; set; }
        public string RUN { get; set; }
        public string Usuario { get; set; }
    }
}
